### ISSUE TITLE
Module Not Found: '../netsuite/set-timeout-polyfill'

### ISSUE THREAD

**Issue by cyberdemic** [globalpayments/node-sdk#13]
I followed instructions:
npm install --save globalpayments-api

In my App I imported:
import * as heartland from "globalpayments-api";

Getting this error when app loads. I am trying to configure globalpayments with my api key.
![heartland-error](https://user-images.githubusercontent.com/54118049/85080150-51d28180-b17d-11ea-8cb9-21a857665e6e.png)

Any suggestions on how to get this to work? I see this repo hasn't been updated in some time. Do you use another repo that is more up to date? Thanks.

**Comment by slogsdon** [comment]
@cyberdemic It looks like you are attempting to use this package in a browser. Is this correct? This package isn't designed to be used from a browser environment as it can cause a merchant account's gateway sensitive credentials to be exposed to the outside world. In addition, some of the bundlers used for client-side apps do not handle the conditional loading we perform for the module in question, and this isn't something we're currently looking at resolving as a protective measure.

**Comment by cyberdemic** [comment]
@slogsdon thank you for the response. I realize now I am using the wrong package.
