### ISSUE TITLE
can't write to logger.txt in production

### ISSUE THREAD

**Issue by hunfajalil-WalQalum** [globalpayments/node-sdk#69]
I am using google cloud functions for deployment. In production when card.charge(2) is trying to write on logger.txt which is not accesible in production. Beacause of that I am getting error in production. In local environment its runninh fine as it has access to logger.txt.
How can i stop it from writing to logger.txt?

**Comment by MilesTFox** [comment]
You need to edit node_modules/globalpayments-api/lib/src/Gateways/XmlGateway.js and comment out the contents of XmlGateway.prototype.log. This is a PCI compliance issue as well, as it saves the entire transaction including all credit card details to disk unencrypted.

Before:

```
 XmlGateway.prototype.log = function (text) {
        fs.appendFile('logger.txt', text + '\n', function (err) {
            if (err)
                throw err;
        });
    };
```

After:
```
 XmlGateway.prototype.log = function (text) {
        /*
        fs.appendFile('logger.txt', text + '\n', function (err) {
            if (err)
                throw err;
        });
        */
    };
```
