### ISSUE TITLE
Help to Integrate the GlobalPayments in React Native..

### ISSUE THREAD

**Issue by RanvijayChouhan12** [globalpayments/node-sdk#72]
I have Looked on the Main Website for both the ANDROID and IOS,

I Read All these Links

IOS : https://developer.globalpay.com/client-side-libraries/ios#ios
ANDROID : https://developer.globalpay.com/client-side-libraries/android#android
SDK : https://developer.globalpay.com/ecommerce/sdks

But all this Didn't help me to integrate this in React native, 

If any one have Ever Integrated GlobalPayments in React Native and can help Please Help.

I am trying this for Long Now

Thanks

**Comment by matrix125** [comment]
Hi,

Going forward, please send all inquiries to the developers group directly.
https://developer.heartlandpaymentsystems.com/Support

Specifically: developers@heartland.us

**Comment by RanvijayChouhan12** [comment]
i Mailed my concern to Above Mail, 

it's been Week and No response, i don't think i will get any Help on This,

thanks, 

i am Closing this Issue.
